---
# Nodes with dedicated SSD (/mnt/ssd)
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-nodes-ssd
spec:
  nodeSelector:
    linstor.linbit.com/storage: ssd
  storagePools:
    - name: pool1
      filePool:
        directory: /mnt/ssd/linstor
---
# metal3 — no dedicated SSD, uses root filesystem
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-nodes-local
spec:
  nodeSelector:
    linstor.linbit.com/storage: local
  storagePools:
    - name: pool1
      filePool:
        directory: /var/lib/linstor
