{
 "title": "TrueNAS dashboard",
 "tags": [
  "TrueNAS",
  "Graphite"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Zaragoza",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "uptime{type=\"uptime\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "uptime",
     "query": "SELECT last(\"value\") FROM \"uptime\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "truenas_local" }
     ]
    }
   ]
  },
  {
   "title": "Current Disk Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "da1",
     "expr": "label_replace(temperature, \"name\", \"$1\", \"type\", \"disktemp-(.*)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "measurement": "da1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "disktemp" }
     ]
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Media Pool",
     "expr": "df_complex_free{type=\"df-mnt-Data\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "mnt-MediaPool",
     "query": "SELECT last(\"value\") FROM \"mnt-MediaPool_df_complex_used\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "df_complex.free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Longterm",
     "expr": "load_longterm{type=\"load\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Longterm",
     "measurement": "load",
     "query": "SELECT * FROM \"vmx0_if_octets_rx\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "longterm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Midterm",
     "expr": "load_midterm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Midterm",
     "measurement": "load",
     "query": "SELECT * FROM \"vmx0_if_octets_rx\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "midterm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Shortterm",
     "expr": "load_shortterm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Shortterm",
     "measurement": "load",
     "query": "SELECT * FROM \"vmx0_if_octets_rx\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "shortterm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Physical Memory Utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Free",
     "expr": "memory_free{type=\"memory\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Free",
     "measurement": "memory",
     "query": "SELECT last(\"value\") FROM \"memory.free\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "ZFS Cache",
     "expr": "cache_size_arc{type=\"zfs_arc\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ZFS",
     "measurement": "cache_size",
     "query": "SELECT last(\"value\") FROM \"memory.active\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "arc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "zfs_arc" }
     ]
    },
    {
     "alias": "Services",
     "expr": "memory_inactive + memory_active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Services",
     "measurement": "cache_size",
     "query": "SELECT last(\"c\")+ last(\"p\")+ last(\"dbuf_size\")+ last(\"dnode_size\")+ last(\"hdr_size\")+ last(\"metadata_size\")+ last(\"mfu_ghost_size\")+ last(\"mfu_size\")+ last(\"mru_ghost_size\")+ last(\"mru_size\") FROM \"cache_size\" WHERE (\"resource\" = 'zfs_arc') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "c" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "zfs_arc" }
     ]
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "da1",
     "expr": "label_replace(temperature, \"name\", \"$1\", \"type\", \"disktemp-(.*)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "measurement": "da1",
     "query": "SELECT * FROM \"da1.temperature\"",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "disktemp" }
     ]
    }
   ]
  },
  {
   "title": "Disk Busy (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "da1",
     "expr": "geom_busy_percent_ada0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ada0",
     "measurement": "geom_busy_percent",
     "select": [
      [
       { "params": [ "da1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "da1",
     "expr": "geom_busy_percent_da0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "da0",
     "measurement": "geom_busy_percent",
     "select": [
      [
       { "params": [ "da1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "da1",
     "expr": "geom_busy_percent_da1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "da1",
     "measurement": "geom_busy_percent",
     "select": [
      [
       { "params": [ "da1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "da1",
     "expr": "geom_busy_percent_da2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "da2",
     "measurement": "geom_busy_percent",
     "select": [
      [
       { "params": [ "da1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Idle",
     "expr": "cpu_idle{type=\"aggregation-cpu-average\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "idle",
     "measurement": "cpu-average",
     "select": [
      [
       { "params": [ "percent.idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Usage",
     "expr": "cpu_interrupt{type=\"aggregation-cpu-average\"} + cpu_system{type=\"aggregation-cpu-average\"} + cpu_nice{type=\"aggregation-cpu-average\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "use",
     "measurement": "cpu-average",
     "query": "SELECT last(\"percent.system\")+ last(\"percent.user\")+ last(\"percent.interrupt\") FROM \"cpu-average\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percent.system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "percent.user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "percent.interrupt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Rx",
     "expr": "if_octets_rx{type=\"interface-re0\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rx",
     "measurement": "vmx0",
     "query": "SELECT * FROM \"vmx0_if_octets_rx\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "if_octets.rx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Tx",
     "expr": "if_octets_tx{type=\"interface-re0\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "tx",
     "measurement": "vmx0",
     "query": "SELECT * FROM \"vmx0_if_octets_rx\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "if_octets.tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Free",
     "expr": "label_replace(temperature, \"name\", \"core-$1\", \"type\", \"cputemp-(.*)\") / 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "measurement": "swap",
     "query": "SELECT last(\"value\") FROM \"memory-free\"\n\n",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZFS ARC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "cache_size_arc", "legendFormat": "ARC" },
    { "expr": "cache_size_mru_size", "legendFormat": "MRU" },
    { "expr": "cache_size_mfu_size", "legendFormat": "MFU" },
    { "expr": "arcstat_ratio_arc_hits", "legendFormat": "hit ratio" }
   ]
  }
 ]
}