---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./reloader/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./snapshot-controller/ks.yaml
