[env]
KUBECONFIG = "{{config_root}}/kubeconfig.yaml"

[tools]
helm = "latest"
k9s = "latest"
kubectl = "latest"
lefthook = "latest"
"pipx:flux-local" = "latest"
task = "latest"
yamlfmt = "latest"

[hooks]
postinstall = "lefthook install"
