[tools]
helm = "latest"
k9s = "latest"
kubectl = "latest"
"npm:@docmd/core" = "latest"
"pipx:flux-local" = "latest"
task = "latest"
[env]
KUBECONFIG = "{{config_root}}/kubeconfig.yaml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
