---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  internal.server: |
    internal.:53 {
      errors
      cache 30
      template IN AAAA {
        rcode NXDOMAIN
      }
      forward . 192.168.1.1
    }
