---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: janitorr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: janitorr-secret
    template:
      data:
        CLIENTS_SONARR_APIKEY: "{{ .SONARR_API_KEY }}"
        CLIENTS_RADARR_APIKEY: "{{ .RADARR_API_KEY }}"
        CLIENTS_JELLYFIN_APIKEY: "{{ .JELLYFIN_API_KEY }}"
        CLIENTS_JELLYFIN_USERNAME: "{{ .JELLYFIN_USERNAME }}"
        CLIENTS_JELLYFIN_PASSWORD: "{{ .JELLYFIN_PASSWORD }}"
        CLIENTS_JELLYSEERR_APIKEY: "{{ .SEERR_API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
        property: SONARR_API_KEY
    - extract:
        key: radarr
        property: RADARR_API_KEY
    - extract:
        key: jellyfin
        property: JELLYFIN_API_KEY
    - extract:
        key: jellyfin
        property: JELLYFIN_USERNAME
    - extract:
        key: jellyfin
        property: JELLYFIN_PASSWORD
    - extract:
        key: seerr
        property: SEERR_API_KEY
