---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./pvc.yaml
configMapGenerator:
  - files:
      - application.yml=./resources/application.yml
    name: janitorr
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  disableNameSuffixHash: true
