---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aurral
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: aurral-secret
    template:
      data:
        LASTFM_API_KEY: "{{ .LASTFM_API_KEY }}"
        LASTFM_API_SECRET: "{{ .LASTFM_API_SECRET }}"
        LIDARR_API_KEY: "{{ .LIDARR_API_KEY }}"
        MUSICBRAINZ_EMAIL: "{{ .MUSICBRAINZ_EMAIL }}"
  dataFrom:
    - extract:
        key: aurral
    - extract:
        key: lidarr
