---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aurral
spec:
  chartRef:
    kind: OCIRepository
    name: aurral
  interval: 1h
  values:
    controllers:
      aurral:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lklynet/aurral
              tag: 1.46.1@sha256:1dcc6e60167af881444290ca2b49d89364b1f19c3196a7eef0162a793bded948
            env:
              TZ: Europe/Madrid
              PORT: &port 3001
              TRUST_PROXY: "1"
              DOWNLOAD_FOLDER: /data/aurral-downloads
              LIDARR_URL: http://lidarr.default.svc.cluster.local
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
        statefulset:
          volumeClaimTemplates:
            - name: data
              storageClass: longhorn
              accessMode: ReadWriteOnce
              size: 5Gi
              globalMounts:
                - path: /app/backend/data
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.atsbhome.xyz"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      downloads:
        type: nfs
        server: truenas.internal
        path: /mnt/torrent/data/Downloads/aurral
        globalMounts:
          - path: /app/downloads
      tmp:
        type: emptyDir
