{
 "title": "Traefik",
 "description": "Traefik dashboard",
 "tags": [ "traefik" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total,exported_service)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,10m,1h,1d,7d" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "OK Response count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"(2|3)\\\\d\\\\d\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "4xx Error Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"4\\\\d\\\\d\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "5xx Error count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"5\\\\d\\\\d\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Top 5 $protocol return code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    traefik_service_requests_total{\r\n      protocol=~\"$protocol\",\r\n      job=~\"$job\",\r\n    }, \r\n  \"response_code\",  \"${1}xx\", \"code\", \"(\\\\d).+\")\r\n)  by (response_code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum( traefik_service_request_duration_seconds_sum{job=~\"$job\",protocol=~\"$protocol\"}\r\n) by (exported_service) /\r\nsum(\r\ntraefik_service_request_duration_seconds_count{job=~\"$job\",protocol=~\"$protocol\"}\r\n) by (exported_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server-side error by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    traefik_service_requests_total{\r\n      job=\"$job\",\r\n      code=~\"5\\\\d\\\\d\",\r\n      protocol=~\"$protocol\" \r\n    }[$interval]\r\n  )\r\n) by (exported_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client-side error by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    traefik_service_requests_total{\r\n      job=\"$job\",\r\n      code=~\"4\\\\d\\\\d\",\r\n      protocol=~\"$protocol\" \r\n    }[$interval]\r\n  )\r\n) by (exported_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "service" },
  {
   "title": "OK code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    traefik_service_requests_total{\r\n      code=~\"(2|3)\\\\d\\\\d\",job=~\"$job\",\r\n      exported_service=~\"$service\",\r\n      protocol=~\"$protocol\"\r\n    }[$interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Error code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    traefik_service_requests_total{\r\n      code=~\"4\\\\d\\\\d\",job=~\"$job\",\r\n      exported_service=~\"$service\",\r\n      protocol=~\"$protocol\"\r\n    }[$interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    traefik_service_requests_total{\r\n      code=~\"5\\\\d\\\\d\",job=~\"$job\",\r\n      exported_service=~\"$service\",\r\n      protocol=~\"$protocol\"\r\n    }[$interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Return code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    traefik_service_requests_total{\r\n      protocol=~\"$protocol\",\r\n      job=~\"$job\",\r\n      exported_service=~\"$service\"\r\n    }, \r\n  \"response_code\",  \"${1}xx\", \"code\", \"(\\\\d).+\")\r\n)  by (response_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum( traefik_service_request_duration_seconds_sum{job=~\"$job\",exported_service=~\"$service\",protocol=~\"$protocol\"}\r\n) by (exported_service) /\r\nsum(\r\ntraefik_service_request_duration_seconds_count{job=~\"$job\",exported_service=~\"$service\",protocol=~\"$protocol\"}\r\n) by (exported_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    traefik_service_requests_total{\r\n      job=\"$job\",\r\n      exported_service=~\"$service\",\r\n    }[$interval]\r\n  )\r\n) by (exported_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "expr": "sum(\r\n traefik_service_open_connections{\r\n  job=~\"$job\", exported_service=~\"$service\"}\r\n) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}