---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.11.10@sha256:f66273e014b307e4ac46778845ebc1e9ee24b2e57c1fc17d5ec5ac3015649bfa
            env:
              TZ: Europe/Madrid
              JELLYFIN_PublishedServerUrl: &loadBalancerIP 192.168.1.36
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              JELLYFIN_FFmpeg__probesize: 50000000
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              readOnlyRootFilesystem: true
              privileged: true # Needed for HW acceleration
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 6Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [39, 44, 105, 104, 100] # cat /etc/group
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: jellyfin
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: *loadBalancerIP
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.atsbhome.xyz
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
        hosts:
          - host: &host "{{ .Release.Name }}.atsbhome.xyz"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: truenas.internal
        path: /mnt/torrent/data
        globalMounts:
          - path: /media
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
