---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-dev-tls
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-dev-tls
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
      metadata:
        annotations:
          cert-manager.io/alt-names: "*.atsbhome.xyz,atsbhome.xyz"
          cert-manager.io/certificate-name: home-dev
          cert-manager.io/common-name: ""
          cert-manager.io/ip-sans: ""
          cert-manager.io/issuer-group: ""
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt-production
          cert-manager.io/uri-sans: ""
        labels:
          controller.cert-manager.io/fao: "true"
  dataFrom:
    - extract:
        key: home-dev-tls
        decodingStrategy: Base64
