---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative_pg_secret
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: aws-access-key-id
      remoteRef:
        key: cloudflare
        property: R2_USER
    - secretKey: aws-secret-access-key
      remoteRef:
        key: cloudflare
        property: R2_PASSWORD
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: cloudflare
        property: CLOUDFLARE_ACCOUNT_TAG
