---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - start: 192.168.1.32
      stop: 192.168.1.63
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  serviceSelector:
    matchExpressions:
      - key: io.kubernetes.service.namespace
        operator: In
        values:
          - network
          - default
          - database
      - key: io.kubernetes.service.name
        operator: In
        values:
          - nginx-external-controller
          - nginx-internal-controller
          - k8s-gateway
          - jellyfin
          - qbittorrent-bittorrent
          - postgres-lb
  externalIPs: true
  loadBalancerIPs: true
