---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: cilium
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  maxHistory: 3

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    hubble:
      serviceMonitor:
        enabled: true
      metrics:
        dashboards:
          enabled: true
      relay:
        prometheus:
          serviceMonitor:
            enabled: true

      ui:
        ingress:
          enabled: false
    l2announcements:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

      relay:
        enabled: false
        prometheus:
          serviceMonitor:
            enabled: true

    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true

    dashboards:
      enabled: true
