#!/bin/bash


INPUT_FILES=$(git diff --name-only --cached)
SECRET_REGEX="^kind:\ssecret$"
SOPS_REGEX="ENC.AES256"
KUSTOMIZE_REGEX="^\$patch:\sdelete"

for var in $INPUT_FILES; do
    if grep -ixq "$SECRET_REGEX" $var
      then
        if grep -iq "$SOPS_REGEX" $var || grep -ixq "$KUSTOMIZE_REGEX" $var
          then
            echo "ok"
          else
            echo "Unencrypted Kubernetes secret detected in file: $var"
            exit 1
        fi
    fi
done
echo "Not found"
exit 0
