{
 "title": "New dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(kube_ingress_info{namespace=~\"$namespace\"},ingress)"
    }
   },
   { "name": "search", "label": "Full text search" }
  ]
 },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(geoip_country_code) (count_over_time({instance=\"nginx-external\"} | json | namespace =~ `$namespace` | ingress =~ `$ingress` | geoip_country_code != `` |= `$search` | http_user_agent !~ `.*UptimeRobot.*` | __error__=`` [$__interval]) )",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({instance=\"nginx-external\"} | json | namespace =~ `$namespace` | ingress =~ `$ingress` | remote_addr != `` | remote_addr !~ `10.244.*` |~ `$search`| http_user_agent !~ `.*UptimeRobot.*` | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({instance=\"nginx-external\"} | json | namespace =~ `$namespace` | ingress =~ `$ingress` | remote_addr != `` | remote_addr !~ `10.244.*`  |~ `$search` |  http_user_agent !~ `.*UptimeRobot.*` | __error__=`` [$__range])))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum by(remote_addr) (count_over_time({instance=\"nginx-external\"} | json | namespace =~ `$namespace` | ingress =~ `$ingress` | remote_addr != `` | remote_addr !~ `10.244.+` |= `$search`| http_user_agent !~ `.*UptimeRobot.*`| __error__=`` [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 4 },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sum by (http_referer) (count_over_time({instance=\"nginx-external\"} | json | namespace=~`$namespace` | ingress=~`$ingress`| http_referer != \"\"|~ `$search`| http_user_agent !~ `.*UptimeRobot.*` | __error__=\"\" [$__interval]))",
     "legendFormat": "{{.http_referer}}"
    }
   ]
  },
  {
   "title": "Recent logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{instance=\"nginx-external\"} | json | namespace =~ `$namespace` | ingress =~ `$ingress` | remote_addr != `` | remote_addr !~ `10.244.*` |= `$search` | http_user_agent !~ `.*UptimeRobot.*` | __error__=`` | line_format `{{.ingress}} {{.request_uri}} {{.remote_addr}}`"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({instance=\"nginx-external\"} | json | namespace=~`$namespace` | ingress=~`$ingress`|~ `$search`| http_user_agent !~ `.*UptimeRobot.*` | __error__=\"\" [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}