---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dilna-pull-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dilna-pull-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .GITHUB_USERNAME }}","auth":"{{ printf "%s:%s" .GITHUB_USERNAME .GITHUB_PAT | b64enc }}"}}}
  dataFrom:
    - extract:
        key: dilna
