---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-nfs
spec:
  jobName: nfs_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitor.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - truenas.internal:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
