---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: flux-system
spec:
  components:
    # Disabled until LINSTOR LVM thin pool is ready (Phase 2)
    # - ../../../../components/volsync
    - ../../../../components/zeroscaler
    - ../../../../components/oci-repository
  dependsOn:
    - name: longhorn
      namespace: flux-system
  interval: 1h
  path: ./kubernetes/apps/media/radarr/app
  postBuild:
    substitute:
      APP: radarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
