---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: flux-system
spec:
  components:
    - ../../../../components/volsync
    - ../../../../components/zeroscaler
  dependsOn:
    - name: piraeus
      namespace: flux-system
  interval: 1h
  path: ./kubernetes/apps/media/radarr/app
  postBuild:
    substitute:
      APP: radarr
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_ACCESSMODES: ReadWriteOnce
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: media
  wait: false
