all:
  vars:
    control_plane_endpoint: 192.168.42.5
    load_balancer_ip_pool:
      - 192.168.42.224/27
metal:
  children:
    masters:
      hosts:
        metal0:
          {
            ansible_host: 192.168.42.10,
            mac: "ec:8e:b5:6d:ff:6f",
            disk: sda,
            network_interface: eno1,
          }
        metal1:
          {
            ansible_host: 192.168.42.20,
            mac: "84:a9:3e:1a:98:43",
            disk: nvme0n1,
            network_interface: enp2s0,
          }
        metal3:
          {
            ansible_host: 192.168.42.30,
            mac: "6c:4b:90:41:9e:23",
            disk: nvme0n1,
            network_interface: enp0s31f6,
          }
