---
originRequest:
  originServerName: external.atsbhome.xyz

ingress:
  - hostname: atsbhome.xyz
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.atsbhome.xyz"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
