---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: paperless
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.16.2
            env:
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SECRET_KEY
              PAPERLESS_URL: https://paperless.atsbhome.xyz
              PAPERLESS_PORT: "8000"
              PAPERLESS_TIME_ZONE: "Europe/Madrid"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_CONSUMPTION_DIR: /data/nas/incoming
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_EXPORT_DIR: /data/nas/export
              PAPERLESS_MEDIA_ROOT: /data/local/media
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              PAPERLESS_OCR_LANGUAGES: spa
              PAPERLESS_OCR_LANGUAGE: spa
              PAPERLESS_REDIS: redis://paperless-redis.default.svc.cluster.local:6379
              USERMAP_GID: "568"
              PAPERLESS_ADMIN_USER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_USER
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_PASSWORD
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 2Gi
              limits:
                memory: 3Gi
      redis:
        containers:
          redis:
            image:
              repository: docker.io/valkey/valkey
              tag: 7.2.13
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        supplementalGroups:
          - 568
    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8000
      redis:
        controller: redis
        ports:
          http:
            port: 6379
    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.atsbhome.xyz"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      data:
        existingClaim: paperless-v1
        advancedMounts:
          paperless:
            app:
              - path: /data/local
      nas:
        type: nfs
        server: 192.168.1.25
        path: /mnt/Data/Paperless
        advancedMounts:
          paperless:
            app:
              - path: /data/nas
