- name: Adjust kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: "fs.inotify.max_queued_events", value: 16384 }
    - { name: "fs.inotify.max_user_instances", value: 8192 }
    - { name: "fs.inotify.max_user_watches", value: 524288 }
    - { name: "vm.nr_hugepages", value: 2048 }

- name: Configure DNS server
  community.general.nmcli:
    conn_name: "{{ network_interface }}"
    type: ethernet
    dns4:
      - "{{ dns_server }}"
    state: present
  register: nmcli_dns
  tags: dns

- name: Apply DNS configuration
  ansible.builtin.command:
    cmd: nmcli con up "{{ network_interface }}"
  when: nmcli_dns.changed
  changed_when: true
  tags: dns

- name: Install Utilities
  ansible.builtin.dnf:
    name:
      - nfs-utils
