---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Disabled until LINSTOR LVM thin pool is ready (Phase 2)
  # - ./volsync/ks.yaml
  # - ./kopia/ks.yaml
