---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
data:
  DB_PORT: "5432"
  TZ: Europe/Madrid
  IMMICH_LOG_LEVEL: verbose
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.default.svc.cluster.local:3003
  IMMICH_SERVER_URL: http://immich-server.default.svc.cluster.local:2283
  IMMICH_WEB_URL: http://immich-web.default.svc.cluster.local:3000
  IMMICH_TRUSTED_PROXIES: 10.42.0.0/16,10.43.0.0/16
  IMMICH_ENV: production
  NODE_ENV: production
  REDIS_URL: ioredis://eyJob3N0IjoiZHJhZ29uZmx5LmRhdGFiYXNlLnN2Yy5jbHVzdGVyLmxvY2FsIiwicG9ydCI6NjM3OSwiZGIiOjE1fQ==
  TRANSFORMERS_CACHE: /usr/src/app/.transformers_cache
  TYPESENSE_DATA_DIR: /config
  TYPESENSE_HOST: immich-typesense.default.svc.cluster.local
