---
name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-docs.yaml"
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: |
          cd docs
          npx @docmd/core build
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./docs/site }
      - uses: actions/deploy-pages@v4
